[<AutoOpen>]
module RInGen.Options

let mutable SECONDS_TIMEOUT = 5 * 60
let MSECONDS_TIMEOUT () = SECONDS_TIMEOUT * 1000
let MEMORY_LIMIT_MB = 4 * 1024

type MODES = VERBOSE_MODE | QUIET_MODE | EXTRA_VERBOSE_MODE
let mutable VERBOSITY_MODE = VERBOSE_MODE
let IN_VERBOSE_MODE () = VERBOSITY_MODE = VERBOSE_MODE || VERBOSITY_MODE = EXTRA_VERBOSE_MODE
let IN_EXTRA_VERBOSE_MODE () = VERBOSITY_MODE = EXTRA_VERBOSE_MODE
