set -x
DEPLOY_BASE_DIR="$(pwd)"
RINGEN_SAMPLES_DIR="$(dirname "$DEPLOY_BASE_DIR")"/samples
cd binaries
TMP_FOLDER="$DEPLOY_BASE_DIR"/tmp
STAREXEC_WALLCLOCK_LIMIT=32 ./starexec_run_cvc $RINGEN_SAMPLES_DIR/test.smt2 $TMP_FOLDER
