//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/columpio/RiderProjects/RInGen/grammar/src/main/resources/SMTLIBv2.g4 by ANTLR 4.9.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace SMTLIB2Parser {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ISMTLIBv2Listener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class SMTLIBv2BaseListener : ISMTLIBv2Listener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStart([NotNull] SMTLIBv2Parser.StartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStart([NotNull] SMTLIBv2Parser.StartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.response"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterResponse([NotNull] SMTLIBv2Parser.ResponseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.response"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitResponse([NotNull] SMTLIBv2Parser.ResponseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.generalReservedWord"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGeneralReservedWord([NotNull] SMTLIBv2Parser.GeneralReservedWordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.generalReservedWord"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGeneralReservedWord([NotNull] SMTLIBv2Parser.GeneralReservedWordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.simpleSymbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleSymbol([NotNull] SMTLIBv2Parser.SimpleSymbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.simpleSymbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleSymbol([NotNull] SMTLIBv2Parser.SimpleSymbolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.quotedSymbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQuotedSymbol([NotNull] SMTLIBv2Parser.QuotedSymbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.quotedSymbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQuotedSymbol([NotNull] SMTLIBv2Parser.QuotedSymbolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.predefSymbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredefSymbol([NotNull] SMTLIBv2Parser.PredefSymbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.predefSymbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredefSymbol([NotNull] SMTLIBv2Parser.PredefSymbolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.predefKeyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredefKeyword([NotNull] SMTLIBv2Parser.PredefKeywordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.predefKeyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredefKeyword([NotNull] SMTLIBv2Parser.PredefKeywordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSymbol([NotNull] SMTLIBv2Parser.SymbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSymbol([NotNull] SMTLIBv2Parser.SymbolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.numeral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumeral([NotNull] SMTLIBv2Parser.NumeralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.numeral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumeral([NotNull] SMTLIBv2Parser.NumeralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.decimal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDecimal([NotNull] SMTLIBv2Parser.DecimalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.decimal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDecimal([NotNull] SMTLIBv2Parser.DecimalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.hexadecimal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHexadecimal([NotNull] SMTLIBv2Parser.HexadecimalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.hexadecimal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHexadecimal([NotNull] SMTLIBv2Parser.HexadecimalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.binary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinary([NotNull] SMTLIBv2Parser.BinaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.binary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinary([NotNull] SMTLIBv2Parser.BinaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString([NotNull] SMTLIBv2Parser.StringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString([NotNull] SMTLIBv2Parser.StringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKeyword([NotNull] SMTLIBv2Parser.KeywordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKeyword([NotNull] SMTLIBv2Parser.KeywordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.spec_constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpec_constant([NotNull] SMTLIBv2Parser.Spec_constantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.spec_constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpec_constant([NotNull] SMTLIBv2Parser.Spec_constantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.s_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterS_expr([NotNull] SMTLIBv2Parser.S_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.s_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitS_expr([NotNull] SMTLIBv2Parser.S_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.index"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndex([NotNull] SMTLIBv2Parser.IndexContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.index"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndex([NotNull] SMTLIBv2Parser.IndexContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] SMTLIBv2Parser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] SMTLIBv2Parser.IdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.attribute_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttribute_value([NotNull] SMTLIBv2Parser.Attribute_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.attribute_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttribute_value([NotNull] SMTLIBv2Parser.Attribute_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttribute([NotNull] SMTLIBv2Parser.AttributeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttribute([NotNull] SMTLIBv2Parser.AttributeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.sort"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSort([NotNull] SMTLIBv2Parser.SortContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.sort"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSort([NotNull] SMTLIBv2Parser.SortContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.qual_identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQual_identifier([NotNull] SMTLIBv2Parser.Qual_identifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.qual_identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQual_identifier([NotNull] SMTLIBv2Parser.Qual_identifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.var_binding"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar_binding([NotNull] SMTLIBv2Parser.Var_bindingContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.var_binding"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar_binding([NotNull] SMTLIBv2Parser.Var_bindingContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.sorted_var"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSorted_var([NotNull] SMTLIBv2Parser.Sorted_varContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.sorted_var"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSorted_var([NotNull] SMTLIBv2Parser.Sorted_varContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPattern([NotNull] SMTLIBv2Parser.PatternContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPattern([NotNull] SMTLIBv2Parser.PatternContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.match_case"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMatch_case([NotNull] SMTLIBv2Parser.Match_caseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.match_case"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMatch_case([NotNull] SMTLIBv2Parser.Match_caseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] SMTLIBv2Parser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] SMTLIBv2Parser.TermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.sort_symbol_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSort_symbol_decl([NotNull] SMTLIBv2Parser.Sort_symbol_declContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.sort_symbol_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSort_symbol_decl([NotNull] SMTLIBv2Parser.Sort_symbol_declContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.meta_spec_constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMeta_spec_constant([NotNull] SMTLIBv2Parser.Meta_spec_constantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.meta_spec_constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMeta_spec_constant([NotNull] SMTLIBv2Parser.Meta_spec_constantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.fun_symbol_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFun_symbol_decl([NotNull] SMTLIBv2Parser.Fun_symbol_declContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.fun_symbol_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFun_symbol_decl([NotNull] SMTLIBv2Parser.Fun_symbol_declContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.par_fun_symbol_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPar_fun_symbol_decl([NotNull] SMTLIBv2Parser.Par_fun_symbol_declContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.par_fun_symbol_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPar_fun_symbol_decl([NotNull] SMTLIBv2Parser.Par_fun_symbol_declContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.theory_attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTheory_attribute([NotNull] SMTLIBv2Parser.Theory_attributeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.theory_attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTheory_attribute([NotNull] SMTLIBv2Parser.Theory_attributeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.theory_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTheory_decl([NotNull] SMTLIBv2Parser.Theory_declContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.theory_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTheory_decl([NotNull] SMTLIBv2Parser.Theory_declContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.logic_attribue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogic_attribue([NotNull] SMTLIBv2Parser.Logic_attribueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.logic_attribue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogic_attribue([NotNull] SMTLIBv2Parser.Logic_attribueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.logic"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogic([NotNull] SMTLIBv2Parser.LogicContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.logic"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogic([NotNull] SMTLIBv2Parser.LogicContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.sort_dec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSort_dec([NotNull] SMTLIBv2Parser.Sort_decContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.sort_dec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSort_dec([NotNull] SMTLIBv2Parser.Sort_decContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.selector_dec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelector_dec([NotNull] SMTLIBv2Parser.Selector_decContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.selector_dec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelector_dec([NotNull] SMTLIBv2Parser.Selector_decContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.constructor_dec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstructor_dec([NotNull] SMTLIBv2Parser.Constructor_decContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.constructor_dec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstructor_dec([NotNull] SMTLIBv2Parser.Constructor_decContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.datatype_dec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDatatype_dec([NotNull] SMTLIBv2Parser.Datatype_decContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.datatype_dec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDatatype_dec([NotNull] SMTLIBv2Parser.Datatype_decContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.function_dec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_dec([NotNull] SMTLIBv2Parser.Function_decContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.function_dec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_dec([NotNull] SMTLIBv2Parser.Function_decContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.function_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_def([NotNull] SMTLIBv2Parser.Function_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.function_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_def([NotNull] SMTLIBv2Parser.Function_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.prop_literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProp_literal([NotNull] SMTLIBv2Parser.Prop_literalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.prop_literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProp_literal([NotNull] SMTLIBv2Parser.Prop_literalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.script"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScript([NotNull] SMTLIBv2Parser.ScriptContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.script"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScript([NotNull] SMTLIBv2Parser.ScriptContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_assert"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmd_assert([NotNull] SMTLIBv2Parser.Cmd_assertContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_assert"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmd_assert([NotNull] SMTLIBv2Parser.Cmd_assertContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_checkSat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmd_checkSat([NotNull] SMTLIBv2Parser.Cmd_checkSatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_checkSat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmd_checkSat([NotNull] SMTLIBv2Parser.Cmd_checkSatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_checkSatAssuming"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmd_checkSatAssuming([NotNull] SMTLIBv2Parser.Cmd_checkSatAssumingContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_checkSatAssuming"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmd_checkSatAssuming([NotNull] SMTLIBv2Parser.Cmd_checkSatAssumingContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_declareConst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmd_declareConst([NotNull] SMTLIBv2Parser.Cmd_declareConstContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_declareConst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmd_declareConst([NotNull] SMTLIBv2Parser.Cmd_declareConstContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_declareDatatype"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmd_declareDatatype([NotNull] SMTLIBv2Parser.Cmd_declareDatatypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_declareDatatype"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmd_declareDatatype([NotNull] SMTLIBv2Parser.Cmd_declareDatatypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_declareDatatypes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmd_declareDatatypes([NotNull] SMTLIBv2Parser.Cmd_declareDatatypesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_declareDatatypes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmd_declareDatatypes([NotNull] SMTLIBv2Parser.Cmd_declareDatatypesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_declareFun"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmd_declareFun([NotNull] SMTLIBv2Parser.Cmd_declareFunContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_declareFun"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmd_declareFun([NotNull] SMTLIBv2Parser.Cmd_declareFunContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_declareSort"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmd_declareSort([NotNull] SMTLIBv2Parser.Cmd_declareSortContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_declareSort"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmd_declareSort([NotNull] SMTLIBv2Parser.Cmd_declareSortContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_defineFun"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmd_defineFun([NotNull] SMTLIBv2Parser.Cmd_defineFunContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_defineFun"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmd_defineFun([NotNull] SMTLIBv2Parser.Cmd_defineFunContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_defineFunRec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmd_defineFunRec([NotNull] SMTLIBv2Parser.Cmd_defineFunRecContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_defineFunRec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmd_defineFunRec([NotNull] SMTLIBv2Parser.Cmd_defineFunRecContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_defineFunsRec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmd_defineFunsRec([NotNull] SMTLIBv2Parser.Cmd_defineFunsRecContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_defineFunsRec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmd_defineFunsRec([NotNull] SMTLIBv2Parser.Cmd_defineFunsRecContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_defineSort"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmd_defineSort([NotNull] SMTLIBv2Parser.Cmd_defineSortContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_defineSort"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmd_defineSort([NotNull] SMTLIBv2Parser.Cmd_defineSortContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_echo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmd_echo([NotNull] SMTLIBv2Parser.Cmd_echoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_echo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmd_echo([NotNull] SMTLIBv2Parser.Cmd_echoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_exit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmd_exit([NotNull] SMTLIBv2Parser.Cmd_exitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_exit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmd_exit([NotNull] SMTLIBv2Parser.Cmd_exitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_getAssertions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmd_getAssertions([NotNull] SMTLIBv2Parser.Cmd_getAssertionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_getAssertions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmd_getAssertions([NotNull] SMTLIBv2Parser.Cmd_getAssertionsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_getAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmd_getAssignment([NotNull] SMTLIBv2Parser.Cmd_getAssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_getAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmd_getAssignment([NotNull] SMTLIBv2Parser.Cmd_getAssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_getInfo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmd_getInfo([NotNull] SMTLIBv2Parser.Cmd_getInfoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_getInfo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmd_getInfo([NotNull] SMTLIBv2Parser.Cmd_getInfoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_getModel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmd_getModel([NotNull] SMTLIBv2Parser.Cmd_getModelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_getModel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmd_getModel([NotNull] SMTLIBv2Parser.Cmd_getModelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_getOption"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmd_getOption([NotNull] SMTLIBv2Parser.Cmd_getOptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_getOption"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmd_getOption([NotNull] SMTLIBv2Parser.Cmd_getOptionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_getProof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmd_getProof([NotNull] SMTLIBv2Parser.Cmd_getProofContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_getProof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmd_getProof([NotNull] SMTLIBv2Parser.Cmd_getProofContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_getUnsatAssumptions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmd_getUnsatAssumptions([NotNull] SMTLIBv2Parser.Cmd_getUnsatAssumptionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_getUnsatAssumptions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmd_getUnsatAssumptions([NotNull] SMTLIBv2Parser.Cmd_getUnsatAssumptionsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_getUnsatCore"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmd_getUnsatCore([NotNull] SMTLIBv2Parser.Cmd_getUnsatCoreContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_getUnsatCore"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmd_getUnsatCore([NotNull] SMTLIBv2Parser.Cmd_getUnsatCoreContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_getValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmd_getValue([NotNull] SMTLIBv2Parser.Cmd_getValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_getValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmd_getValue([NotNull] SMTLIBv2Parser.Cmd_getValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_pop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmd_pop([NotNull] SMTLIBv2Parser.Cmd_popContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_pop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmd_pop([NotNull] SMTLIBv2Parser.Cmd_popContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_push"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmd_push([NotNull] SMTLIBv2Parser.Cmd_pushContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_push"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmd_push([NotNull] SMTLIBv2Parser.Cmd_pushContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_reset"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmd_reset([NotNull] SMTLIBv2Parser.Cmd_resetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_reset"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmd_reset([NotNull] SMTLIBv2Parser.Cmd_resetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_resetAssertions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmd_resetAssertions([NotNull] SMTLIBv2Parser.Cmd_resetAssertionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_resetAssertions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmd_resetAssertions([NotNull] SMTLIBv2Parser.Cmd_resetAssertionsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_setInfo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmd_setInfo([NotNull] SMTLIBv2Parser.Cmd_setInfoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_setInfo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmd_setInfo([NotNull] SMTLIBv2Parser.Cmd_setInfoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_setLogic"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmd_setLogic([NotNull] SMTLIBv2Parser.Cmd_setLogicContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_setLogic"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmd_setLogic([NotNull] SMTLIBv2Parser.Cmd_setLogicContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_setOption"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmd_setOption([NotNull] SMTLIBv2Parser.Cmd_setOptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_setOption"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmd_setOption([NotNull] SMTLIBv2Parser.Cmd_setOptionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.command"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommand([NotNull] SMTLIBv2Parser.CommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.command"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommand([NotNull] SMTLIBv2Parser.CommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.b_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterB_value([NotNull] SMTLIBv2Parser.B_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.b_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitB_value([NotNull] SMTLIBv2Parser.B_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.option"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOption([NotNull] SMTLIBv2Parser.OptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.option"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOption([NotNull] SMTLIBv2Parser.OptionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.info_flag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInfo_flag([NotNull] SMTLIBv2Parser.Info_flagContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.info_flag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInfo_flag([NotNull] SMTLIBv2Parser.Info_flagContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.error_behaviour"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterError_behaviour([NotNull] SMTLIBv2Parser.Error_behaviourContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.error_behaviour"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitError_behaviour([NotNull] SMTLIBv2Parser.Error_behaviourContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.reason_unknown"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReason_unknown([NotNull] SMTLIBv2Parser.Reason_unknownContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.reason_unknown"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReason_unknown([NotNull] SMTLIBv2Parser.Reason_unknownContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.model_response"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModel_response([NotNull] SMTLIBv2Parser.Model_responseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.model_response"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModel_response([NotNull] SMTLIBv2Parser.Model_responseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.info_response"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInfo_response([NotNull] SMTLIBv2Parser.Info_responseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.info_response"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInfo_response([NotNull] SMTLIBv2Parser.Info_responseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.valuation_pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValuation_pair([NotNull] SMTLIBv2Parser.Valuation_pairContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.valuation_pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValuation_pair([NotNull] SMTLIBv2Parser.Valuation_pairContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.t_valuation_pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterT_valuation_pair([NotNull] SMTLIBv2Parser.T_valuation_pairContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.t_valuation_pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitT_valuation_pair([NotNull] SMTLIBv2Parser.T_valuation_pairContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.check_sat_response"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCheck_sat_response([NotNull] SMTLIBv2Parser.Check_sat_responseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.check_sat_response"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCheck_sat_response([NotNull] SMTLIBv2Parser.Check_sat_responseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.echo_response"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEcho_response([NotNull] SMTLIBv2Parser.Echo_responseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.echo_response"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEcho_response([NotNull] SMTLIBv2Parser.Echo_responseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.get_assertions_response"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGet_assertions_response([NotNull] SMTLIBv2Parser.Get_assertions_responseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.get_assertions_response"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGet_assertions_response([NotNull] SMTLIBv2Parser.Get_assertions_responseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.get_assignment_response"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGet_assignment_response([NotNull] SMTLIBv2Parser.Get_assignment_responseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.get_assignment_response"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGet_assignment_response([NotNull] SMTLIBv2Parser.Get_assignment_responseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.get_info_response"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGet_info_response([NotNull] SMTLIBv2Parser.Get_info_responseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.get_info_response"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGet_info_response([NotNull] SMTLIBv2Parser.Get_info_responseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.get_model_response"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGet_model_response([NotNull] SMTLIBv2Parser.Get_model_responseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.get_model_response"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGet_model_response([NotNull] SMTLIBv2Parser.Get_model_responseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.get_option_response"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGet_option_response([NotNull] SMTLIBv2Parser.Get_option_responseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.get_option_response"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGet_option_response([NotNull] SMTLIBv2Parser.Get_option_responseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.get_proof_response"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGet_proof_response([NotNull] SMTLIBv2Parser.Get_proof_responseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.get_proof_response"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGet_proof_response([NotNull] SMTLIBv2Parser.Get_proof_responseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.get_unsat_assump_response"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGet_unsat_assump_response([NotNull] SMTLIBv2Parser.Get_unsat_assump_responseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.get_unsat_assump_response"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGet_unsat_assump_response([NotNull] SMTLIBv2Parser.Get_unsat_assump_responseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.get_unsat_core_response"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGet_unsat_core_response([NotNull] SMTLIBv2Parser.Get_unsat_core_responseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.get_unsat_core_response"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGet_unsat_core_response([NotNull] SMTLIBv2Parser.Get_unsat_core_responseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.get_value_response"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGet_value_response([NotNull] SMTLIBv2Parser.Get_value_responseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.get_value_response"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGet_value_response([NotNull] SMTLIBv2Parser.Get_value_responseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.specific_success_response"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpecific_success_response([NotNull] SMTLIBv2Parser.Specific_success_responseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.specific_success_response"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpecific_success_response([NotNull] SMTLIBv2Parser.Specific_success_responseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.general_response"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGeneral_response([NotNull] SMTLIBv2Parser.General_responseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.general_response"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGeneral_response([NotNull] SMTLIBv2Parser.General_responseContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace SMTLIB2Parser
