//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/columpio/RiderProjects/RInGen/grammar/src/main/resources/SMTLIBv2.g4 by ANTLR 4.9.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace SMTLIB2Parser {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="SMTLIBv2Parser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.1")]
[System.CLSCompliant(false)]
public interface ISMTLIBv2Listener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStart([NotNull] SMTLIBv2Parser.StartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStart([NotNull] SMTLIBv2Parser.StartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.response"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterResponse([NotNull] SMTLIBv2Parser.ResponseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.response"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitResponse([NotNull] SMTLIBv2Parser.ResponseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.generalReservedWord"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGeneralReservedWord([NotNull] SMTLIBv2Parser.GeneralReservedWordContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.generalReservedWord"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGeneralReservedWord([NotNull] SMTLIBv2Parser.GeneralReservedWordContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.simpleSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleSymbol([NotNull] SMTLIBv2Parser.SimpleSymbolContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.simpleSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleSymbol([NotNull] SMTLIBv2Parser.SimpleSymbolContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.quotedSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuotedSymbol([NotNull] SMTLIBv2Parser.QuotedSymbolContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.quotedSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuotedSymbol([NotNull] SMTLIBv2Parser.QuotedSymbolContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.predefSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPredefSymbol([NotNull] SMTLIBv2Parser.PredefSymbolContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.predefSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPredefSymbol([NotNull] SMTLIBv2Parser.PredefSymbolContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.predefKeyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPredefKeyword([NotNull] SMTLIBv2Parser.PredefKeywordContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.predefKeyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPredefKeyword([NotNull] SMTLIBv2Parser.PredefKeywordContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.symbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSymbol([NotNull] SMTLIBv2Parser.SymbolContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.symbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSymbol([NotNull] SMTLIBv2Parser.SymbolContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.numeral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumeral([NotNull] SMTLIBv2Parser.NumeralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.numeral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumeral([NotNull] SMTLIBv2Parser.NumeralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.decimal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDecimal([NotNull] SMTLIBv2Parser.DecimalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.decimal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDecimal([NotNull] SMTLIBv2Parser.DecimalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.hexadecimal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHexadecimal([NotNull] SMTLIBv2Parser.HexadecimalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.hexadecimal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHexadecimal([NotNull] SMTLIBv2Parser.HexadecimalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.binary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinary([NotNull] SMTLIBv2Parser.BinaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.binary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinary([NotNull] SMTLIBv2Parser.BinaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString([NotNull] SMTLIBv2Parser.StringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString([NotNull] SMTLIBv2Parser.StringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeyword([NotNull] SMTLIBv2Parser.KeywordContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeyword([NotNull] SMTLIBv2Parser.KeywordContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.spec_constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpec_constant([NotNull] SMTLIBv2Parser.Spec_constantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.spec_constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpec_constant([NotNull] SMTLIBv2Parser.Spec_constantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.s_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterS_expr([NotNull] SMTLIBv2Parser.S_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.s_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitS_expr([NotNull] SMTLIBv2Parser.S_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.index"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndex([NotNull] SMTLIBv2Parser.IndexContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.index"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndex([NotNull] SMTLIBv2Parser.IndexContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier([NotNull] SMTLIBv2Parser.IdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier([NotNull] SMTLIBv2Parser.IdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.attribute_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttribute_value([NotNull] SMTLIBv2Parser.Attribute_valueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.attribute_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttribute_value([NotNull] SMTLIBv2Parser.Attribute_valueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttribute([NotNull] SMTLIBv2Parser.AttributeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttribute([NotNull] SMTLIBv2Parser.AttributeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.sort"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSort([NotNull] SMTLIBv2Parser.SortContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.sort"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSort([NotNull] SMTLIBv2Parser.SortContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.qual_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQual_identifier([NotNull] SMTLIBv2Parser.Qual_identifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.qual_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQual_identifier([NotNull] SMTLIBv2Parser.Qual_identifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.var_binding"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar_binding([NotNull] SMTLIBv2Parser.Var_bindingContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.var_binding"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar_binding([NotNull] SMTLIBv2Parser.Var_bindingContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.sorted_var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSorted_var([NotNull] SMTLIBv2Parser.Sorted_varContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.sorted_var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSorted_var([NotNull] SMTLIBv2Parser.Sorted_varContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPattern([NotNull] SMTLIBv2Parser.PatternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPattern([NotNull] SMTLIBv2Parser.PatternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.match_case"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMatch_case([NotNull] SMTLIBv2Parser.Match_caseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.match_case"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMatch_case([NotNull] SMTLIBv2Parser.Match_caseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerm([NotNull] SMTLIBv2Parser.TermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerm([NotNull] SMTLIBv2Parser.TermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.sort_symbol_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSort_symbol_decl([NotNull] SMTLIBv2Parser.Sort_symbol_declContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.sort_symbol_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSort_symbol_decl([NotNull] SMTLIBv2Parser.Sort_symbol_declContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.meta_spec_constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMeta_spec_constant([NotNull] SMTLIBv2Parser.Meta_spec_constantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.meta_spec_constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMeta_spec_constant([NotNull] SMTLIBv2Parser.Meta_spec_constantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.fun_symbol_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFun_symbol_decl([NotNull] SMTLIBv2Parser.Fun_symbol_declContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.fun_symbol_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFun_symbol_decl([NotNull] SMTLIBv2Parser.Fun_symbol_declContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.par_fun_symbol_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPar_fun_symbol_decl([NotNull] SMTLIBv2Parser.Par_fun_symbol_declContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.par_fun_symbol_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPar_fun_symbol_decl([NotNull] SMTLIBv2Parser.Par_fun_symbol_declContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.theory_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTheory_attribute([NotNull] SMTLIBv2Parser.Theory_attributeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.theory_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTheory_attribute([NotNull] SMTLIBv2Parser.Theory_attributeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.theory_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTheory_decl([NotNull] SMTLIBv2Parser.Theory_declContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.theory_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTheory_decl([NotNull] SMTLIBv2Parser.Theory_declContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.logic_attribue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogic_attribue([NotNull] SMTLIBv2Parser.Logic_attribueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.logic_attribue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogic_attribue([NotNull] SMTLIBv2Parser.Logic_attribueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.logic"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogic([NotNull] SMTLIBv2Parser.LogicContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.logic"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogic([NotNull] SMTLIBv2Parser.LogicContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.sort_dec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSort_dec([NotNull] SMTLIBv2Parser.Sort_decContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.sort_dec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSort_dec([NotNull] SMTLIBv2Parser.Sort_decContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.selector_dec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelector_dec([NotNull] SMTLIBv2Parser.Selector_decContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.selector_dec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelector_dec([NotNull] SMTLIBv2Parser.Selector_decContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.constructor_dec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstructor_dec([NotNull] SMTLIBv2Parser.Constructor_decContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.constructor_dec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstructor_dec([NotNull] SMTLIBv2Parser.Constructor_decContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.datatype_dec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDatatype_dec([NotNull] SMTLIBv2Parser.Datatype_decContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.datatype_dec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDatatype_dec([NotNull] SMTLIBv2Parser.Datatype_decContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.function_dec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_dec([NotNull] SMTLIBv2Parser.Function_decContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.function_dec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_dec([NotNull] SMTLIBv2Parser.Function_decContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.function_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_def([NotNull] SMTLIBv2Parser.Function_defContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.function_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_def([NotNull] SMTLIBv2Parser.Function_defContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.prop_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProp_literal([NotNull] SMTLIBv2Parser.Prop_literalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.prop_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProp_literal([NotNull] SMTLIBv2Parser.Prop_literalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScript([NotNull] SMTLIBv2Parser.ScriptContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScript([NotNull] SMTLIBv2Parser.ScriptContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_assert"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmd_assert([NotNull] SMTLIBv2Parser.Cmd_assertContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_assert"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmd_assert([NotNull] SMTLIBv2Parser.Cmd_assertContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_checkSat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmd_checkSat([NotNull] SMTLIBv2Parser.Cmd_checkSatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_checkSat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmd_checkSat([NotNull] SMTLIBv2Parser.Cmd_checkSatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_checkSatAssuming"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmd_checkSatAssuming([NotNull] SMTLIBv2Parser.Cmd_checkSatAssumingContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_checkSatAssuming"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmd_checkSatAssuming([NotNull] SMTLIBv2Parser.Cmd_checkSatAssumingContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_declareConst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmd_declareConst([NotNull] SMTLIBv2Parser.Cmd_declareConstContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_declareConst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmd_declareConst([NotNull] SMTLIBv2Parser.Cmd_declareConstContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_declareDatatype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmd_declareDatatype([NotNull] SMTLIBv2Parser.Cmd_declareDatatypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_declareDatatype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmd_declareDatatype([NotNull] SMTLIBv2Parser.Cmd_declareDatatypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_declareDatatypes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmd_declareDatatypes([NotNull] SMTLIBv2Parser.Cmd_declareDatatypesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_declareDatatypes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmd_declareDatatypes([NotNull] SMTLIBv2Parser.Cmd_declareDatatypesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_declareFun"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmd_declareFun([NotNull] SMTLIBv2Parser.Cmd_declareFunContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_declareFun"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmd_declareFun([NotNull] SMTLIBv2Parser.Cmd_declareFunContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_declareSort"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmd_declareSort([NotNull] SMTLIBv2Parser.Cmd_declareSortContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_declareSort"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmd_declareSort([NotNull] SMTLIBv2Parser.Cmd_declareSortContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_defineFun"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmd_defineFun([NotNull] SMTLIBv2Parser.Cmd_defineFunContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_defineFun"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmd_defineFun([NotNull] SMTLIBv2Parser.Cmd_defineFunContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_defineFunRec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmd_defineFunRec([NotNull] SMTLIBv2Parser.Cmd_defineFunRecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_defineFunRec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmd_defineFunRec([NotNull] SMTLIBv2Parser.Cmd_defineFunRecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_defineFunsRec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmd_defineFunsRec([NotNull] SMTLIBv2Parser.Cmd_defineFunsRecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_defineFunsRec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmd_defineFunsRec([NotNull] SMTLIBv2Parser.Cmd_defineFunsRecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_defineSort"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmd_defineSort([NotNull] SMTLIBv2Parser.Cmd_defineSortContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_defineSort"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmd_defineSort([NotNull] SMTLIBv2Parser.Cmd_defineSortContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_echo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmd_echo([NotNull] SMTLIBv2Parser.Cmd_echoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_echo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmd_echo([NotNull] SMTLIBv2Parser.Cmd_echoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_exit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmd_exit([NotNull] SMTLIBv2Parser.Cmd_exitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_exit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmd_exit([NotNull] SMTLIBv2Parser.Cmd_exitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_getAssertions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmd_getAssertions([NotNull] SMTLIBv2Parser.Cmd_getAssertionsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_getAssertions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmd_getAssertions([NotNull] SMTLIBv2Parser.Cmd_getAssertionsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_getAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmd_getAssignment([NotNull] SMTLIBv2Parser.Cmd_getAssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_getAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmd_getAssignment([NotNull] SMTLIBv2Parser.Cmd_getAssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_getInfo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmd_getInfo([NotNull] SMTLIBv2Parser.Cmd_getInfoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_getInfo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmd_getInfo([NotNull] SMTLIBv2Parser.Cmd_getInfoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_getModel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmd_getModel([NotNull] SMTLIBv2Parser.Cmd_getModelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_getModel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmd_getModel([NotNull] SMTLIBv2Parser.Cmd_getModelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_getOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmd_getOption([NotNull] SMTLIBv2Parser.Cmd_getOptionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_getOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmd_getOption([NotNull] SMTLIBv2Parser.Cmd_getOptionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_getProof"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmd_getProof([NotNull] SMTLIBv2Parser.Cmd_getProofContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_getProof"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmd_getProof([NotNull] SMTLIBv2Parser.Cmd_getProofContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_getUnsatAssumptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmd_getUnsatAssumptions([NotNull] SMTLIBv2Parser.Cmd_getUnsatAssumptionsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_getUnsatAssumptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmd_getUnsatAssumptions([NotNull] SMTLIBv2Parser.Cmd_getUnsatAssumptionsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_getUnsatCore"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmd_getUnsatCore([NotNull] SMTLIBv2Parser.Cmd_getUnsatCoreContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_getUnsatCore"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmd_getUnsatCore([NotNull] SMTLIBv2Parser.Cmd_getUnsatCoreContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_getValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmd_getValue([NotNull] SMTLIBv2Parser.Cmd_getValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_getValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmd_getValue([NotNull] SMTLIBv2Parser.Cmd_getValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_pop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmd_pop([NotNull] SMTLIBv2Parser.Cmd_popContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_pop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmd_pop([NotNull] SMTLIBv2Parser.Cmd_popContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_push"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmd_push([NotNull] SMTLIBv2Parser.Cmd_pushContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_push"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmd_push([NotNull] SMTLIBv2Parser.Cmd_pushContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_reset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmd_reset([NotNull] SMTLIBv2Parser.Cmd_resetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_reset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmd_reset([NotNull] SMTLIBv2Parser.Cmd_resetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_resetAssertions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmd_resetAssertions([NotNull] SMTLIBv2Parser.Cmd_resetAssertionsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_resetAssertions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmd_resetAssertions([NotNull] SMTLIBv2Parser.Cmd_resetAssertionsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_setInfo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmd_setInfo([NotNull] SMTLIBv2Parser.Cmd_setInfoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_setInfo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmd_setInfo([NotNull] SMTLIBv2Parser.Cmd_setInfoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_setLogic"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmd_setLogic([NotNull] SMTLIBv2Parser.Cmd_setLogicContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_setLogic"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmd_setLogic([NotNull] SMTLIBv2Parser.Cmd_setLogicContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.cmd_setOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmd_setOption([NotNull] SMTLIBv2Parser.Cmd_setOptionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.cmd_setOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmd_setOption([NotNull] SMTLIBv2Parser.Cmd_setOptionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommand([NotNull] SMTLIBv2Parser.CommandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommand([NotNull] SMTLIBv2Parser.CommandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.b_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterB_value([NotNull] SMTLIBv2Parser.B_valueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.b_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitB_value([NotNull] SMTLIBv2Parser.B_valueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOption([NotNull] SMTLIBv2Parser.OptionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOption([NotNull] SMTLIBv2Parser.OptionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.info_flag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInfo_flag([NotNull] SMTLIBv2Parser.Info_flagContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.info_flag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInfo_flag([NotNull] SMTLIBv2Parser.Info_flagContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.error_behaviour"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterError_behaviour([NotNull] SMTLIBv2Parser.Error_behaviourContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.error_behaviour"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitError_behaviour([NotNull] SMTLIBv2Parser.Error_behaviourContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.reason_unknown"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReason_unknown([NotNull] SMTLIBv2Parser.Reason_unknownContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.reason_unknown"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReason_unknown([NotNull] SMTLIBv2Parser.Reason_unknownContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.model_response"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModel_response([NotNull] SMTLIBv2Parser.Model_responseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.model_response"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModel_response([NotNull] SMTLIBv2Parser.Model_responseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.info_response"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInfo_response([NotNull] SMTLIBv2Parser.Info_responseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.info_response"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInfo_response([NotNull] SMTLIBv2Parser.Info_responseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.valuation_pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValuation_pair([NotNull] SMTLIBv2Parser.Valuation_pairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.valuation_pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValuation_pair([NotNull] SMTLIBv2Parser.Valuation_pairContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.t_valuation_pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterT_valuation_pair([NotNull] SMTLIBv2Parser.T_valuation_pairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.t_valuation_pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitT_valuation_pair([NotNull] SMTLIBv2Parser.T_valuation_pairContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.check_sat_response"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCheck_sat_response([NotNull] SMTLIBv2Parser.Check_sat_responseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.check_sat_response"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCheck_sat_response([NotNull] SMTLIBv2Parser.Check_sat_responseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.echo_response"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEcho_response([NotNull] SMTLIBv2Parser.Echo_responseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.echo_response"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEcho_response([NotNull] SMTLIBv2Parser.Echo_responseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.get_assertions_response"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGet_assertions_response([NotNull] SMTLIBv2Parser.Get_assertions_responseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.get_assertions_response"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGet_assertions_response([NotNull] SMTLIBv2Parser.Get_assertions_responseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.get_assignment_response"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGet_assignment_response([NotNull] SMTLIBv2Parser.Get_assignment_responseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.get_assignment_response"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGet_assignment_response([NotNull] SMTLIBv2Parser.Get_assignment_responseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.get_info_response"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGet_info_response([NotNull] SMTLIBv2Parser.Get_info_responseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.get_info_response"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGet_info_response([NotNull] SMTLIBv2Parser.Get_info_responseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.get_model_response"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGet_model_response([NotNull] SMTLIBv2Parser.Get_model_responseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.get_model_response"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGet_model_response([NotNull] SMTLIBv2Parser.Get_model_responseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.get_option_response"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGet_option_response([NotNull] SMTLIBv2Parser.Get_option_responseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.get_option_response"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGet_option_response([NotNull] SMTLIBv2Parser.Get_option_responseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.get_proof_response"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGet_proof_response([NotNull] SMTLIBv2Parser.Get_proof_responseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.get_proof_response"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGet_proof_response([NotNull] SMTLIBv2Parser.Get_proof_responseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.get_unsat_assump_response"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGet_unsat_assump_response([NotNull] SMTLIBv2Parser.Get_unsat_assump_responseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.get_unsat_assump_response"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGet_unsat_assump_response([NotNull] SMTLIBv2Parser.Get_unsat_assump_responseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.get_unsat_core_response"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGet_unsat_core_response([NotNull] SMTLIBv2Parser.Get_unsat_core_responseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.get_unsat_core_response"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGet_unsat_core_response([NotNull] SMTLIBv2Parser.Get_unsat_core_responseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.get_value_response"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGet_value_response([NotNull] SMTLIBv2Parser.Get_value_responseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.get_value_response"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGet_value_response([NotNull] SMTLIBv2Parser.Get_value_responseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.specific_success_response"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpecific_success_response([NotNull] SMTLIBv2Parser.Specific_success_responseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.specific_success_response"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpecific_success_response([NotNull] SMTLIBv2Parser.Specific_success_responseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SMTLIBv2Parser.general_response"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGeneral_response([NotNull] SMTLIBv2Parser.General_responseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SMTLIBv2Parser.general_response"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGeneral_response([NotNull] SMTLIBv2Parser.General_responseContext context);
}
} // namespace SMTLIB2Parser
